image: gitpod/workspace-full

tasks:
  - init: |
      sudo chsh -s $(which zsh)
      gem install jekyll bundler
      bundle install
    command: |
      sudo chsh -s $(which zsh)
      bundle exec jekyll serve --port 8080

ports:
  - port: 8080
    onOpen: open-browser

github:
  prebuilds:
    master: true
    pullRequests: true
    addBadge: true
    addLabel: true