name: Composerize Drupal
year_created: 2018
source: https://github.com/grasmash/composerize-drupal
homepage: https://github.com/grasmash/composerize-drupal
docs:
logo:

description: "Convert a non-Composer-managed Drupal application (e.g., one created via tarball) to a Composer-managed Drupal application."

requires:
  - composer
drupal_versions:
  - 8
  - 9
category:
  - cli
  - development
  - deprecated
similar:
