name: Optimize Composer for Drupal projects
year_created: 2018
source: https://github.com/zaporylie/composer-drupal-optimizations
homepage: https://github.com/zaporylie/composer-drupal-optimizations
docs:
logo:

description: "This composer-plugin contains a set of improvements that makes
running heavy duty composer commands (i.e. composer update or
composer require) much faster."

requires:
  - composer
drupal_versions:
  - 8
category:
  - cli
  - development
similar:
